In [ ]:
# Creating dataset
import pandas as pd
import numpy as np

np.random.seed(42)

n = 120

data = {
    "age": np.random.randint(18, 65, n),
    "monthly_income": np.random.randint(1000, 10000, n),
    "spending_score": np.random.randint(1, 100, n),
    "city": np.random.choice(["Accra", "Kumasi", "Tema", "Takoradi"], n),
    "subscription_type": np.random.choice(["Basic", "Standard", "Premium"], n)

}

df = pd.DataFrame(data)

# Introduce missing values randomly
for col in df.columns:
    df.loc[df.sample(frac=0.1).index, col] = np.nan

# Introducinng extreme outliers in the monthly income column

      age  monthly_income  spending_score    city subscription_type
0    56.0          9996.0            60.0    Tema           Premium
1     NaN          3731.0             2.0   Accra          Standard
2    32.0          9154.0             1.0  Kumasi           Premium
3    60.0          6056.0            48.0    Tema             Basic
4    25.0          9110.0            12.0  Kumasi          Standard
..    ...             ...             ...     ...               ...
115  25.0          6534.0            17.0    Tema             Basic
116  29.0          5061.0            33.0   Accra           Premium
117  51.0          1262.0             9.0  Kumasi             Basic
118  50.0          7287.0             NaN   Accra           Premium
119  40.0          9815.0            48.0    Tema          Standard

[120 rows x 5 columns]

In [5]:
df.describe(include="all")
# df.info()

               age  monthly_income  spending_score    city subscription_type
count   108.000000      108.000000      108.000000     108               108
unique         NaN             NaN             NaN       4                 3
top            NaN             NaN             NaN  Kumasi             Basic
freq           NaN             NaN             NaN      28                48
mean     41.148148     5745.750000       47.120370     NaN               NaN
std      14.165784     2560.342402       27.993897     NaN               NaN
min      18.000000     1202.000000        1.000000     NaN               NaN
25%      28.750000     3479.500000       24.750000     NaN               NaN
50%      41.000000     5993.500000       45.000000     NaN               NaN
75%      54.250000     7962.250000       67.000000     NaN               NaN
max      64.000000     9996.000000       99.000000     NaN               NaN

In [2]:
## Step 1
## Usually to check you data for missing values and how best to clean your data
df.isnull().sum()

age                  12
monthly_income       12
spending_score       12
city                 12
subscription_type    12
dtype: int64

In [7]:
## replacing missing data with median because its often the default safer bet and only because this is a learning test set
df["age"] = df["age"].fillna(df["age"].median())
df["monthly_income"] = df["monthly_income"].fillna(df["monthly_income"].median())
df["spending_score"]=df["spending_score"].fillna(df["spending_score"].median())

## Filling categorical data with the mode
df["city"] = df["city"].fillna(df["city"].mode()[0])
df["subscription_type"] = df["subscription_type"].fillna(df["subscription_type"].mode()[0])

df.isnull().sum()

age                  0
monthly_income       0
spending_score       0
city                 0
subscription_type    0
dtype: int64